# Generated by Django 2.1.4 on 2019-01-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlipModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flipName', models.CharField(max_length=100)),
                ('flipBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Flip_Vendor',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('productQty', models.IntegerField()),
                ('fliProducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkarts.FlipModel')),
            ],
            options={
                'db_table': 'Flip_Product',
            },
        ),
    ]
