# Generated by Django 2.1.4 on 2019-01-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkarts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flipmodel',
            table='Flip_Vendor1',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Flip_Product1',
        ),
    ]
