# Generated by Django 2.1.4 on 2019-01-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkarts', '0002_auto_20190102_1404'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flipmodel',
            table='Vendor1',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product1',
        ),
    ]
